import re
from src.procesamiento.normalizacion import normalizar_texto_busqueda

MATERIAS_RELEVANTES = {
    # Penal
    "lavado de activos", "estafa", "enriquecimiento ilicito", "falsificacion",
    "peculado", "trafico de influencias",
    # Civil / Mercantil
    "insolvencia", "quiebra", "cobro de facturas", "ejecucion de garantias",
    "juicio ejecutivo", "dominio", "nulidad", "contractual", "danos y perjuicios",
    # Laboral
    "laboral",
    # Tributario / Administrativo
    # (pendiente: sin palabras clave definidas aún)
    # Inquilinato / Constitucional
    "inquilinato", "constitucional",
    # NOTA: "accion de proteccion" se removió de aquí a propósito -
    # confirmado en reunión que la lista de exclusión oficial (más abajo)
    # tiene prioridad y la excluye siempre. Dejarla aquí sería código
    # muerto, ya que la exclusión se revisa antes que la relevancia.
}

# Lista oficial de materias/tipos de proceso a EXCLUIR, provista por el
# equipo legal (reunión del 29/07/2026). Se mantiene como texto plano
# para poder actualizarla fácilmente pegando una lista nueva completa,
# sin tener que editar un set() de Python a mano.
_LISTA_EXCLUSION_RAW = """
CONSTITUCIONAL

ACCION DE ACCESO A LA INFORMACION PUBLICA
ACCION DE HABEAS CORPUS
ACCION DE HABEAS DATA
ACCION DE PROTECCION
ACCION DE PROTECCION POR VIOLACION AL DERECHO AL CUIDADO EN EL AMBITO LABORAL
ACCION EXTRAORDINARIA DE PROTECCION
ACCION EXTRAORDINARIA DE PROTECCION CONTRA DECISIONES DE LA JUSTICIA INDIGENA

CIVIL COGEP

ACCION POR DESPIDO INEFICAZ
ACEPTACION AL CARGO DE ALBACEA
ACEPTACION O REPUDIO DE HERENCIA
ADOPCION
ADOPCION INTERNACIONAL
ALIMENTOS CON PRESUNCION DE PATERNIDAD
ALIMENTOS PARA PERSONAS ADULTAS MAYORES
ANULACION DE PARTIDA DE ESTADO CIVIL
APERTURA DE LA SUCESION HEREDITARIA
APERTURA DE TESTAMENTO CERRADO
APROBACION DE ACTA DE MEDIACION CON OPOSICION
APROBACION DE ACTA TRANSACCIONAL
APTITUD PARA ADOPTABILIDAD
AQUELLAS EN QUE POR SU NATURALEZA O POR RAZON DEL ESTADO DE LAS COSAS, SE RESUELVAN SIN CONTRADICCION ART.334
ART. 14 COGEP CONFLICTO DE COMPETENCIA
AUTORIZACION DE DONACION A MENOR DE EDAD
AUTORIZACION DE HIPOTECA DE BIEN DE MENOR
AUTORIZACION DE SALIDA DEL PAIS
AUTORIZACION DE TUTELA O CURADURIA PARA SEGUNDAS NUPCIAS
AUTORIZACION DE VENTA DE BIEN DE INTERDICTO
AUTORIZACION DE VENTA DE BIEN DE MENOR DE EDAD
AUTORIZACION DE VENTA DE BIENES DE NIÑAS, NIÑOS Y ADOLESCENTES Y, DE PERSONAS SOMETIDAS A GUARDA
AUTORIZACION JUDICIAL DE REEMBOLSO DE ANTICIPOS AL PUPILO
AUTORIZACION JUDICIAL O LICENCIA ART. 334 COGEP
AUTORIZACION JUDICIAL PARA LA ADMINISTRACION DE LA SOCIEDAD CONYUGAL
AUTORIZACION JUDICIAL PARA LA CONSTITUCION DE PATRIMONIO FAMILIAR
AUTORIZACION JUDICIAL PARA VENTA DE MERCADERIA EN NAVES
AUTORIZACION PARA EL DESCERRAJAMIENTO DEL LOCAL COMERCIAL CERRADO
AUTORIZACION PARA INSCRIPCION DE ESCRITURA CON OPOSICION
AUTORIZACION PARA INSCRIPCION DE LIQUIDACION DE LA SOCIEDAD CONYUGAL
CADUCIDAD DEL DERECHO DE ALIMENTOS POR ACTA DE MEDIACION
CESION DE COMPETENCIA
CESION DE LA PATRIA POTESTAD
CESION DE TENENCIA
CLAUSURA DE ESTABLECIMIENTOS
CONFERIMIENTO DE LA PATRIA POTESTAD
CONSENTIMIENTO DE ADOPTABILIDAD
CONTRA ACTOS ADMINISTRATIVOS POR SILENCIO ADMINISTRATIVO
CONTRA CIRCULARES DE CARACTER GENERAL
CONTRA DECISION DE PREFERENCIA DE CREDITOS ART. 176 CODIGO TRIBUTARIO
CONTRA DECISIONES ADMNISTRATIVAS DICTADAS EN RECURSO DE REVISION
CONTRA NEGATIVA DE LO DEBIDAMENTE PAGADO
CONTRA NEGATIVA DE PAGO EN EXCESO
CONTRA NEGATIVA DE PAGO INDEBIDO
CONTRA NEGATIVA DE PETICION DE COMPENSACION
CONTRA NEGATIVA DE PETICION DE FACILIDADES DE PAGO
CONTRA ORDENANZAS
CONTRA REGLAMENTOS
CONTRA RESOLUCIONES
CONTRA RESOLUCIONES ADMNISTRATIVAS QUE IMPONGAN SANCIONES
CONTRATOS DE PRENDA ESPECIAL DE COMERCIO
CUSTODIA DE EMERGENCIA DEL NIÑO, NIÑA O ADOLESCENTE AFECTADO
CUSTODIA DE LAS PERSONAS ADULTAS MAYORES
DECLARACION DE MUERTE PRESUNTA
DECLARACION DE PARTE HECHA CON JURAMENTO ANTE UNA O UN JUZGADOR COMPETENTE
DECLARACION JUDICIAL DE PATERNIDAD
DECLARATORIA DE MUERTE PRESUNTA
DECLARATORIA DE UNION DE HECHO
DESPIDO INTEMPESTIVO
DISENSO PARA MATRIMONIO DE MENORES DE EDAD
DISOLUCION DE LA SOCIEDAD CONYUGAL
DISOLUCION DE LA SOCIEDAD DE BIENES DE UNION DE HECHO
DISOLUCION DE LAS ASOCIACIONES PROFESIONALES O SINDICATOS
DIVERGENCIA EN ENTREGA MATERIAL DE BIENES REMATADOS O SUBASTADOS
DIVORCIO POR CAUSAL
DIVORCIO POR MUTUO CONSENTIMIENTO
EMANCIPACION VOLUNTARIA
EXCEPCIONES
EXCEPCIONES A LA COACTIVA
EXCEPCIONES AL PROCEDIMIENTO DE EJECUCION
EXCLUSION DE BIENES DE INVENTARIO
EXCLUSION DE BIENES DE LA PARTICION
EXCLUSION DE SOCIO
EXONERACION DE INVENTARIO DE BIENES
EXTINCION DE LA OBLIGACION DE ALIMENTOS
HABERSE PRESENTADO DEMANDA CONTENCIOSO TRIBUTARIA POR IMPUGNACION DE RESOLUCION ADMINISTRATIVA, ANTECEDENTE DEL TITULO O TITULOS QUE SE EJECUTAN
IMPUGNACION DE LA UNION DE HECHO
IMPUGNACION DE MATERNIDAD
IMPUGNACION DE PATERNIDAD
IMPUGNACION DE VISTO BUENO
IMPUGNACION DEL ACTA DE FINIQUITO
IMPUGNACION DEL DOCUMENTO DE FINIQUITO
IMPUGNACION DEL RECONOCIMIENTO VOLUNTARIO DE HIJO O HIJA
INCAPACIDAD EXCUSA Y REMOCION DE LOS GUARDADORES
INCIDENTE DE VISITAS
INDEMNIZACION POR ACCIDENTE DE TRABAJO
INDEMNIZACION POR DESPIDO INTEMPESTIVO
INDEMNIZACION POR ENFERMEDAD PROFESIONAL
INDIGNIDAD
INSCRICPION TARDIA DE MATRIMONIOS
INSCRICPION TARDIA DE UNION DE HECHO
INSCRIPCION TARDIA DE DEFUNCIONES
INSCRIPCION TARDIA DE NACIMIENTO
JUBILACION
JUICIO DE FILIACION Y PRUEBAS DEL ESTADO CIVIL
LIMITACION DE LA PATRIA POTESTAD
LIQUIDACION DE BIENES DE LA SOCIEDAD CONYUGAL
LIQUIDACION DE BIENES DE LA UNION DE HECHO
MEDIDAS DE PROTECCION FMNA
MEJORAS
MODIFICACION AL REGIMEN DE VISITAS
NEGATIVA AL CARGO DE ALBACEA
NEGATIVA DE INSCRIPCION DE MATRIMONIOS
NEGATIVA DE INSCRIPCION DE TESTAMENTO
NEGATIVA DE INSCRIPCION DEFUNCIONES
NEGATIVA DE INSCRIPCION NACIMIENTOS
NEGATIVA DE LA INSCRIPCION DE LA DECLARATORIA DE UNION DE HECHO SOLEMNIZADA ANTE NOTARIO PUBLICO.
NOMBRAMIENTO DE TUTORA O TUTOR O CURADORA O CURADOR
NOTIFICACION AL ALBACEA
NULIDAD DE MATRIMONIO
NULIDAD DE PARTICION
NULIDAD DE PROCEDIMIENTO COACTIVO
NULIDAD DEL ACTO DE RECONOCIMIENTO DE PATERNIDAD
NULIDAD O REFORMA DE PARTIDA O INSCRIPCION
OBJECION A LAS CUENTAS
OBRA NUEVA
OPOSICION A LA RENDICION DE CUENTAS
OPOSICION AL DESAHUCIO
OPOSICION TRAMITES NOTARIALES
PAGO DE HABERES LABORALES
PARTICION CON OPOSICION
PARTICION DE BIENES DE LA SOCIEDAD CONYUGAL
PARTICION DE BIENES DE LA UNION DE HECHO
PARTICION DE BIENES ENTRE COPROPIETARIOS
PARTICION DE BIENES SUCESORIOS
PARTICION DE BIENES Y DEMARCACION DE LINDEROS CON OPOSICION
PARTICION Y ADJUDICACION DE BIENES DE SOCIEDAD CIVIL
PATRIA POTESTAD VOLUNTARIA
POSESION NOTORIA DE NOMBRES Y APELLIDOS
POSESION NOTORIA DEL ESTADO DE MATRIMONIO
PRIVACION O PERDIDA DE LA PATRIA POTESTAD
PROPIEDAD INTELECTUAL (DERECHOS DE AUTOR)
PROTOCOLIZACION DE TESTAMENTO OTORGADO ANTE LA PRESENCIA DE CINCO TESTIGOS ART. 11058 CODIGO CIVIL
RECONOCIMIENTO DE CAPITULACIONES MATRIMONIALES OTORGADAS EN EL EXTRANJERO
RECONOCIMIENTO DE DOCUMENTO PRIVADO
RECONOCIMIENTO DE HIJO POSTUMO
RECONOCIMIENTO VOLUNTARIO
RECONOCIMIENTO Y HOMOLOGACION DE ACTA DE MEDIACION EXTRANJERA
RECONOCIMIENTO Y HOMOLOGACION DE LAUDO ARBITRAL EXTRANJERO
RECONOCIMIENTO Y HOMOLOGACION DE SENTENCIA EXTRANJERA
RECUPERACION DE INTERDICTO
RECURSO DE QUEJA
REFORMA O MODIFICACION DE NOMBRAMIENTO DE TUTOR
REGIMEN DE VISITAS
REGIMEN DE VISITAS DE LAS Y A LAS PERSONAS ADULTAS MAYORES
REHABILITACION DE INTERDICCION
REMOCION DE CURADOR
REMUNERACIONES MENSUALES ADICIONALES IMPAGAS
RESCICION DEL CONTRATO DE RENUNCIA DE GANANCIALES DE LA SOCIEDAD CONYUGAL
RESPONSABILIDAD OBJETIVA DEL ESTADO
RESTITUCION DE LA PATRIA POTESTAD
RESTITUCION INTERNACIONAL
REVOCATORIA DE DESHEREDAMIENTO
REVOCATORIA DE DONACION
REVOCATORIA DE EMANCIPACION VOLUNTARIA
SILENCIO ADMNISTRATIVO POSITIVO
SOLICITUD DE REBAJA DE PENSION DE ARRENDAMIENTO
SUBROGACION DE PATRIMONIO FAMILIAR
SUSPENSION DE LA PATRIA POTESTAD
TERMINACION DE LA RELACION LABORAL
TERMINACION DE LA SEPARACION DE LA SOCIEDAD CONYUGAL
TERMINACION DE LA UNION DE HECHO
TUTELA O CURADURIA

COIP

ART. 072 EXTINCION DE LA PENA
ART. 098 REALIZACION DE PROCEDIMIENTOS DE TRASPLANTE SIN AUTORIZACION
ART. 106 PROMESA DE MATRIMONIO O UNION DE HECHO SERVIL
ART. 107 ADOPCION ILEGAL
ART. 108 EMPLEO DE PERSONAS PARA MENDICIDAD
ART. 131 ABOLICION Y SUSPENSION DE DERECHOS DE PERSONA PROTEGIDA
ART. 134 OMISION DE MEDIDAS DE SOCORRO Y ASISTENCIA HUMANITARIA
ART. 135 OMISION DE MEDIDAS DE PROTECCION
ART. 137 PROLONGACION DE HOSTILIDADES
ART. 147 ABORTO CON MUERTE
ART. 148 ABORTO NO CONSENTIDO
ART. 149 ABORTO CONSENTIDO
ART. 153 ABANDONO DE PERSONA
ART. 154.3 ACOSO ESCOLAR Y ACADEMICO
ART. 156 VIOLENCIA FISICA CONTRA LA MUJER O MIEMBROS DEL NUCLEO FAMILIAR
ART. 157 VIOLENCIA PSICOLOGICA CONTRA LA MUJER O MIEMBROS DEL NUCLEO FAMILIAR
ART. 159 CONTRAVENCIONES DE VIOLENCIA CONTRA LA MUJER O MIEMBROS DEL NUCLEO FAMILIAR
ART. 164 INSEMINACION NO CONSENTIDA
ART. 176 DISCRIMINACION
ART. 180 DIFUSION DE INFORMACION DE CIRCULACION RESTRINGIDA
ART. 182 CALUMNIA
ART. 183 RESTRICCION A LA LIBERTAD DE EXPRESION
ART. 184 RESTRICCION A LA LIBERTAD DE CULTO
ART. 188 APROVECHAMIENTO ILICITO DE SERVICIOS PUBLICOS
ART. 190 APROPIACION FRAUDULENTA POR MEDIOS ELECTRONICOS
ART. 191 REPROGRAMACION O MODIFICACION DE INFORMACION DE EQUIPOS TERMINALES MOVILES
ART. 193 REEMPLAZO DE IDENTIFICACION DE TERMINALES MOVILES
ART. 194 COMERCIALIZACION ILICITA DE TERMINALES MOVILES
ART. 195 INFRAESTRUCTURA ILICITA
ART. 199 ABIGEATO
ART. 208 A FALSIFICACION DE MARCAS Y PIRATERIA LESIVA CONTRA LOS DERECHOS DE AUTOR
ART. 208 OCULTAMIENTO Y OTROS ACTOS FRAUDULENTOS EN BENEFICIO DEL FALLIDO
ART. 216 CONTAMINACION DE SUSTANCIAS DESTINADAS AL CONSUMO HUMANO
ART. 217 COMERCIALIZACION, DISTRIBUCION, IMPORTACION, ALMACENAMIENTO Y DISPENSACION DE MEDICAMENTOS, DISPOSITIVOS MEDICOS Y PRODUCTOS DE USO Y CONSUMO HUMANO CADUCADOS
ART. 217.1 PRODUCCION, FABRICACION, COMERCIALIZACION, DISTRIBUCION, IMPORTACION, ALMACENAMIENTO O DISPENSACION DE MEDICAMENTOS, DISPOSITIVOS MEDICOS Y PRODUCTOS DE USO Y CONSUMO HUMANO FALSIFICADOS O ADULTERADOS
ART. 218 DESATENCION DEL SERVICIO DE SALUD
ART. 222 SIEMBRA O CULTIVO
ART. 224 PRESCRIPCION INJUSTIFICADA
ART. 229 REVELACION ILEGAL DE BASE DE DATOS
ART. 230 INTERCEPTACION ILEGAL DE DATOS
ART. 232 ATAQUE A LA INTEGRIDAD DE SISTEMAS INFORMATICOS
ART. 233 DELITOS CONTRA LA INFORMACION PUBLICA RESERVADA LEGALMENTE
ART. 234 ACCESO NO CONSENTIDO A UN SISTEMA INFORMATICO, TELEMATICO O DE TELECOMUNICACIONES
ART. 237 DESTRUCCION DE BIENES DEL PATRIMONIO CULTURAL
ART. 238 TRANSPORTE Y COMERCIALIZACION ILICITOS Y TRAFICO DE BIENES DEL PATRIMONIO CULTURAL
ART. 239 FALSIFICACION O ADULTERACION DE BIENES DEL PATRIMONIO CULTURAL
ART. 240 SUSTRACCION DE BIENES DEL PATRIMONIO CULTURAL
ART. 242 RETENCION ILEGAL DE APORTACION A LA SEGURIDAD SOCIAL
ART. 243 FALTA DE AFILIACION AL INSTITUTO ECUATORIANO DE SEGURIDAD SOCIAL POR PARTE DE UNA PERSONA JURIDICA
ART. 244 FALTA DE AFILIACION AL INSTITUTO ECUATORIANO DE SEGURIDAD SOCIAL
ART. 246 INCENDIOS FORESTALES Y DE VEGETACION
ART. 247 DELITOS CONTRA LA FLORA Y FAUNA SILVESTRES
ART. 248 DELITOS CONTRA LOS RECURSOS DEL PATRIMONIO GENETICO NACIONAL
ART. 249 LESIONES A ANIMALES QUE FORMEN PARTE DEL AMBITO DE LA FAUNA URBANA
ART. 253 CONTAMINACION DEL AIRE
ART. 255 FALSEDAD U OCULTAMIENTO DE INFORMACION AMBIENTAL
ART. 262 PARALIZACION DEL SERVICIO DE DISTRIBUCION DE COMBUSTIBLES
ART. 263 ADULTERACION DE LA CALIDAD O CANTIDAD DE PRODUCTOS DERIVADOS DE HIDROCARBUROS, GAS LICUADO DE PETROLEO O BIOCOMBUSTIBLES
ART. 264 ALMACENAMIENTO, TRANSPORTE, ENVASADO, COMERCIALIZACION O DISTRIBUCION ILEGAL O MAL USO DE PRODUCTOS DERIVADOS DE HIDROCARBUROS, GAS LICUADO DE PETROLEO O BIOCOMBUSTIBLES
ART. 265 ALMACENAMIENTO, TRANSPORTE, ENVASADO, COMERCIALIZACION O DISTRIBUCION ILEGAL DE HIDROCARBUROS EN LAS PROVINCIAS FRONTERIZAS, PUERTOS MARITIMOS O FLUVIALES O MAR TERRITORIAL
ART. 270 PERJURIO Y FALSO TESTIMONIO
ART. 274 EVASION
ART. 275 INGRESO DE ARTICULOS PROHIBIDOS
ART. 276 OMISION DE DENUNCIA POR PARTE DE UN PROFESIONAL DE LA SALUD
ART. 277 OMISION DE DENUNCIA
ART. 282 INCUMPLIMIENTO DE DECISIONES LEGITIMAS DE AUTORIDAD COMPETENTE
ART. 283 ATAQUE O RESISTENCIA
ART. 284 RUPTURA DE SELLOS
ART. 288 USO DE FUERZA PUBLICA CONTRA ORDENES DE AUTORIDAD
ART. 290 DELITOS CONTRA LOS BIENES INSTITUCIONALES DE FUERZAS ARMADAS O POLICIA NACIONAL
ART. 291 ELUSION DE RESPONSABILIDADES DE LAS O LOS SERVIDORES DE LAS FUERZAS ARMADAS O POLICIA NACIONAL
ART. 292 ALTERACION DE EVIDENCIAS Y ELEMENTOS DE PRUEBA
ART. 293 EXTRALIMITACION EN LA EJECUCION DE UN ACTO DE SERVICIO
ART. 294 ABUSO DE FACULTADES
ART. 295 NEGATIVA A PRESTAR AUXILIO SOLICITADO POR AUTORIDAD CIVIL
ART. 308 AGIOTAJE
ART. 311 OCULTAMIENTO DE INFORMACION
ART. 321 ACTOS ILEGALES TENDIENTES AL ALZA DE PRECIOS DE PRODUCTOS SUJETOS A PRECIO OFICIAL
ART. 328.1 FALSEDAD DE CONTENIDO EN RECETAS, EXAMENES O CERTIFICADOS MEDICOS
ART. 329 FALSIFICACION, FORJAMIENTO O ALTERACION DE RECETAS
ART. 331 OBSTACULIZACION DE PROCESO ELECTORAL
ART. 332 SUSTRACCION DE PAPELETAS ELECTORALES
ART. 333 FALSO SUFRAGIO
ART. 334 FRAUDE ELECTORAL
ART. 342 SEDICION
ART. 343 INSUBORDINACION
ART. 344 ABSTENCION DE LA EJECUCION DE OPERACIONES EN CONMOCION INTERNA
ART. 346 PARALIZACION DE UN SERVICIO PUBLICO
ART. 348 INCITACION A DISCORDIA ENTRE CIUDADANOS
ART. 357 DESERCION
ART. 358 OMISION DE AVISO DE DESERCION
ART. 364 INCENDIO
ART. 365 APOLOGIA
ART. 381 EXCESO DE PASAJEROS EN TRANSPORTE PUBLICO
ART. 382 DAÑOS MECANICOS PREVISIBLES EN TRANSPORTE PUBLICO
ART. 383 CONDUCCION DE VEHICULO CON LLANTAS EN MAL ESTADO
ART. 384 CONDUCCION DE VEHICULO BAJO EFECTO DE SUSTANCIAS ESTUPEFACIENTES, PSICOTROPICAS O PREPARADOS QUE LAS CONTENGAN
ART. 385 CONDUCCION DE VEHICULO EN ESTADO DE EMBRIAGUEZ
ART. 386 CONTRAVENCIONES DE TRANSITO DE PRIMERA CLASE
ART. 387 CONTRAVENCIONES DE TRANSITO DE SEGUNDA CLASE
ART. 388 CONTRAVENCIONES DE TRANSITO DE TERCERA CLASE
ART. 389 CONTRAVENCIONES DE TRANSITO DE CUARTA CLASE
ART. 390 CONTRAVENCIONES DE TRANSITO DE QUINTA CLASE
ART. 391 CONTRAVENCIONES DE TRANSITO DE SEXTA CLASE
ART. 392 CONTRAVENCIONES DE TRANSITO DE SEPTIMA CLASE
ART. 393 CONTRAVENCIONES DE PRIMERA CLASE
ART. 394 CONTRAVENCIONES DE SEGUNDA CLASE
ART. 395 CONTRAVENCIONES DE TERCERA CLASE
ART. 396 CONTRAVENCIONES DE CUARTA CLASE
ART. 397 CONTRAVENCIONES EN ESCENARIOS DEPORTIVOS Y DE CONCURRENCIA MASIVA
BENEFICIOS Y PETICIONES DE PERSONAS PRIVADAS DE LA LIBERTAD
INDULTO
"""

_ENCABEZADOS_SECCION = {"CONSTITUCIONAL", "CIVIL COGEP", "COIP"}
_PATRON_PREFIJO_ARTICULO = re.compile(r'^ART\.\s*\d+(?:\.\d+)?\s*(?:[A-Z]\s+)?', re.IGNORECASE)


def _construir_materias_excluidas() -> set:
    """
    Procesa la lista oficial cruda: quita encabezados de sección, quita
    el prefijo 'ART. 123 ' de las entradas del COIP (el texto real
    capturado del portal normalmente no incluye la palabra "ART."), y
    normaliza cada frase con el mismo normalizador usado en todo el
    sistema, para que la comparación sea consistente.
    """
    excluidas = set()
    for linea in _LISTA_EXCLUSION_RAW.strip().split("\n"):
        linea = linea.strip()
        if not linea or linea.upper() in _ENCABEZADOS_SECCION:
            continue
        sin_prefijo = _PATRON_PREFIJO_ARTICULO.sub("", linea).strip()
        normalizada = normalizar_texto_busqueda(sin_prefijo)
        if normalizada:
            excluidas.add(normalizada)
    return excluidas


MATERIAS_EXCLUIDAS = _construir_materias_excluidas()


def es_materia_relevante(materia_o_accion: str) -> bool:
    """
    Recibe el texto de 'materia' o, si no está disponible, el texto de
    'Acción/Infracción/Delito'.

    NOTA: esta función es una primera pasada por palabras/frases clave.
    No es infalible - un abogado debe seguir revisando los casos límite.

    DECISIÓN CONFIRMADA (reunión 29/07/2026): ante conflicto entre la
    lista oficial de exclusión y la lista de relevantes, la exclusión
    oficial SIEMPRE gana (se revisa primero en el código). Esto incluye
    casos que antes se consideraban relevantes por defecto, como
    "DESPIDO INTEMPESTIVO" / "INDEMNIZACIÓN POR DESPIDO INTEMPESTIVO"
    (ahora excluidos) y "ACCIÓN DE PROTECCIÓN" (ahora excluida, pese a
    estar también en la lista de relevantes de Constitucional).
    """
    texto_normalizado = normalizar_texto_busqueda(materia_o_accion).lower()

    if any(excluida.lower() in texto_normalizado for excluida in MATERIAS_EXCLUIDAS):
        return False

    if any(relevante in texto_normalizado for relevante in MATERIAS_RELEVANTES):
        return True

    return True  # decisión conservadora: mejor mostrar de más que ocultar algo importante

# Mapeo de palabra clave -> categoría general, para la columna "Temática
# Juicios" de la matriz. Usa las mismas palabras que ya están en
# MATERIAS_RELEVANTES, agrupadas por categoría explícita.
_CATEGORIA_POR_PALABRA = {
    # Penal
    "lavado de activos": "Penal", "estafa": "Penal", "enriquecimiento ilicito": "Penal",
    "falsificacion": "Penal", "peculado": "Penal", "trafico de influencias": "Penal",
    "archivo de la investigacion previa": "Penal", "investigacion previa": "Penal",
    # Civil / Mercantil
    "insolvencia": "Civil/Mercantil", "quiebra": "Civil/Mercantil",
    "cobro de facturas": "Civil/Mercantil", "ejecucion de garantias": "Civil/Mercantil",
    "juicio ejecutivo": "Civil/Mercantil", "dominio": "Civil/Mercantil",
    "nulidad": "Civil/Mercantil", "contractual": "Civil/Mercantil",
    "danos y perjuicios": "Civil/Mercantil", "facturas": "Civil/Mercantil",
    # Laboral
    "laboral": "Laboral",
    # Inquilinato / Constitucional
    "inquilinato": "Inquilinato/Constitucional", "constitucional": "Inquilinato/Constitucional",
}


def clasificar_categoria(materia_o_accion: str) -> str:
    """
    Determina la categoría general (Civil/Mercantil, Penal, Laboral,
    Inquilinato/Constitucional) de un proceso, para la columna "Temática
    Juicios" de la matriz. Reutiliza las mismas palabras clave que
    es_materia_relevante(), sin duplicar la lista.
    """
    texto_normalizado = normalizar_texto_busqueda(materia_o_accion).lower()

    for palabra, categoria in _CATEGORIA_POR_PALABRA.items():
        if palabra in texto_normalizado:
            return categoria

    return ""  # no coincide con ninguna categoría conocida